# Generated by Django 6.0.4 on 2026-04-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='Sesión ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20, verbose_name='Rol')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('size', models.CharField(max_length=20, verbose_name='Talla')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Imagen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
